title: 天才まくまくノート
name: 天才まくまくノート
url: https://ojisancancode.github.io
baseurl: ""
img_dir: /assets/img
logo: /assets/img/logo.jpg
keep_files: [assets]
sass:
  sass_dir: /assets/css/_sass
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap

exclude:
  - "*.bat"
  - "*.cmd"
  - "*.jekyll-metadata"
  - "*.json"
  - "*.sh"
  - "*.yaml"
  - "*.yml"
  - ".*"
  - Gemfile
  - Gemfile.lock
  - LOCAL_MEMO.md
  - README.md
  - gemfiles/
  - hugo-files/
  - node_modules/
  - tools/
  - vendor/

# Enable highlighter.
# highlighter: pygments
highlighter: rouge

# Parse markdown files just like GitHub Flavored Markdown.
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false  # Not insert BR for each line

# Layout settings.
defaults:
  -
    scope:
      path: ""  # an empty string here means all files in the project
      type: "pages"  # exclude raw files such as files in the css directory
    values:
      layout: "default"  # use _layout/default.html
      category_id: "NONE"
      category_desc: "天才星人まくのソフトウェア開発に関するノート"
      category_logo: "logo.jpg"
      category_og_image: "logo.jpg"

  # この「いろいろ」カテゴリだけトップに表示するため、
  # 最初に定義しておく（残りはアルファベット順）
  -
    scope:
      path: "memo"
      type: "pages"
    values:
      category_title: "いろいろ"
      category_id: "memo"
      category_logo: "logo-program.svg"
      category_og_image: "logo-program.svg"
      category_desc: "天才星人まくのごちゃまぜノート"
      category_long_desc: "ソフトウェア開発のベストプラクティス、現場での気付き、ブックレビューなど。"

  -
    scope:
      path: "android"
      type: "pages"
    values:
      category_title: "Android"
      category_id: "android"
      category_logo: "logo-android.jpg"
      category_og_image: "logo-android.jpg"
      category_desc: "天才星人まくのAndroidノート"
      category_long_desc: "Android スマホアプリ、Android TV の開発に関して。"
  -
    scope:
      path: "ansible"
      type: "pages"
    values:
      category_title: "Ansible"
      category_id: "ansible"
      category_logo: "logo-ansible.svg"
      category_og_image: "logo-ansible.png"
      category_desc: "天才星人まくのAnsibleノート"
      category_long_desc: "これからの構成管理は Ansible で！ DevOps の要！ Infrastructur as Code！"
  -
    scope:
      path: "blender"
      type: "pages"
    values:
      category_title: "Blender"
      category_id: "blender"
      category_logo: "logo-blender.svg"
      category_og_image: "logo-blender.png"
      category_desc: "天才星人まくのBlenderノート"
      category_long_desc: "3DCG を描くなら Blender で！ アニメーションも作れるよ。"
  -
    scope:
      path: "cpp"
      type: "pages"
    values:
      category_title: "C/C++"
      category_id: "cpp"
      category_logo: "logo-cpp.svg"
      category_og_image: "logo-cpp.png"
      category_desc: "天才星人まくのC/C++ノート"
      category_long_desc: "ポインタポインタポインター！"
  -
    scope:
      path: "docker"
      type: "pages"
    values:
      category_title: "Docker"
      category_id: "docker"
      category_logo: "logo-docker.png"
      category_og_image: "logo-docker.png"
      category_desc: "天才星人まくのDockerノート"
      category_long_desc: "アプリケーション実行環境をコンテナ化し、柔軟なデプロイを可能にする Docker の使い方。"
  -
    scope:
      path: "git"
      type: "pages"
    values:
      category_title: "Git"
      category_id: "git"
      category_logo: "logo-github.png"
      category_og_image: "logo-github.png"
      category_desc: "天才星人まくのGit/GitHubノート"
      category_long_desc: "Git によるバージョン管理と、GitHub 特有の話もあるよ。"
  -
    scope:
      path: "go"
      type: "pages"
    values:
      category_title: "Go言語"
      category_id: "go"
      category_logo: "logo-go.svg"
      category_og_image: "logo-go.png"
      category_desc: "天才星人まくの Go 言語ノート"
      category_long_desc: "Go 言語 (Golang) 入門。各種 OS に対応した高速な実行ファイルを作成できます。"
  -
    scope:
      path: "gradle"
      type: "pages"
    values:
      category_title: "Gradle"
      category_id: "gradle"
      category_logo: "logo-gradle.png"
      category_og_image: "logo-gradle.png"
      category_desc: "天才星人まくのGradleノート"
      category_long_desc: "Java の最新のビルドシステム Gradle の使い方。"
  -
    scope:
      path: "web"
      type: "pages"
    values:
      category_title: "HTML/CSS"
      category_id: "web"
      category_logo: "logo-html5.svg"
      category_og_image: "logo-html5.png"
      category_desc: "天才星人まくのHTML/CSSノート"
      category_long_desc: "スタイルシートの使い方や、Web 用パーツサンプルなど。"
  -
    scope:
      path: "hugo"
      type: "pages"
    values:
      category_title: "Hugo"
      category_id: "hugo"
      category_logo: "logo-hugo.png"
      category_og_image: "logo-hugo.png"
      category_desc: "天才星人まくの Hugo ノート"
      category_long_desc: "高速な静的サイトジェネレータ Hugo の使い方。"
  -
    scope:
      path: "java"
      type: "pages"
    values:
      category_title: "Java"
      category_id: "java"
      category_logo: "logo-java.svg"
      category_og_image: "logo-java.png"
      category_desc: "天才星人まくのJavaノート"
      category_long_desc: "Android のおかげで息を吹き返した感のある Java。"
  -
    scope:
      path: "js"
      type: "pages"
    values:
      category_title: "JavaScript"
      category_id: "js"
      category_logo: "logo-js.svg"
      category_og_image: "logo-js.png"
      category_desc: "天才星人まくのJavaScriptノート"
      category_long_desc: "Web プログラマにとって必須の言語。"
  -
    scope:
      path: "kotlin"
      type: "pages"
    values:
      category_title: "Kotlin"
      category_id: "kotlin"
      category_logo: "logo-kotlin.svg"
      category_og_image: "logo-kotlin.png"
      category_desc: "天才星人まくのKotlinノート"
      category_long_desc: "Androidの公式サポートによって一気にメジャーになったKotlin。Javaでコーディングしたくなったときは、先にKotlinの採用を検討しましょう。"
  -
    scope:
      path: "linux"
      type: "pages"
    values:
      category_title: "Linux/Shell"
      category_id: "linux"
      category_logo: "logo-linux.svg"
      category_og_image: "logo-linux.png"
      category_desc: "天才星人まくのLinux/Shellノート"
      category_long_desc: "Linux 全般のメモ。Bash や Linux シェルプログラミングなど。"
  -
    scope:
      path: "mac"
      type: "pages"
    values:
      category_title: "Mac"
      category_id: "mac"
      category_logo: "logo-mac.svg"
      category_og_image: "logo-mac.png"
      category_desc: "天才星人まくのMacノート"
      category_long_desc: "Mac OS 関連のメモ。"
  -
    scope:
      path: "middleman"
      type: "pages"
    values:
      category_title: "Middleman"
      category_id: "middleman"
      category_logo: "logo-middleman.svg"
      category_og_image: "logo-middleman.png"
      category_desc: "天才星人まくのMiddlemanノート"
      category_long_desc: "静的サイトジェネレータ Middleman の使い方。"
  -
    scope:
      path: "mt"
      type: "pages"
    values:
      category_title: "Meta Trader"
      category_id: "mt"
      category_logo: "logo-metatrader.png"
      category_og_image: "logo-metatrader.png"
      category_desc: "天才星人まくの Meta Trader ノート"
      category_long_desc: "メタトレーダーを使った FX 自動売買（シストレ）プログラミングについて。"
  -
    scope:
      path: "nodejs"
      type: "pages"
    values:
      category_title: "Node.js"
      category_id: "nodejs"
      category_logo: "logo-nodejs.svg"
      category_og_image: "logo-nodejs.png"
      category_desc: "天才星人まくの Node JS ノート"
      category_long_desc: "今やクライアントもサーバも Node.js でバッチシ。"
  -
    scope:
      path: "octave"
      type: "pages"
    values:
      category_title: "Octave"
      category_id: "octave"
      category_logo: "logo-octave.svg"
      category_og_image: "logo-octave.png"
      category_desc: "天才星人まくのOctaveノート"
      category_long_desc: "MATLAB 互換な数値解析ソフト Octave。グラフも描けるよ！"
  -
    scope:
      path: "p4"
      type: "pages"
    values:
      category_title: "Perforce"
      category_id: "p4"
      category_logo: "logo-p4.jpg"
      category_og_image: "logo-p4.jpg"
      category_desc: "天才星人まくのPerforceノート"
      category_long_desc: "p4 コマンドや p4v についていろいろ。"
  -
    scope:
      path: "perl"
      type: "pages"
    values:
      category_title: "Perl"
      category_id: "perl"
      category_logo: "logo-perl.svg"
      category_og_image: "logo-perl.png"
      category_desc: "天才星人まくのPerlノート"
      category_long_desc: "おそらくもうオワコンな言語、Perl。"
  -
    scope:
      path: "php"
      type: "pages"
    values:
      category_title: "PHP"
      category_id: "php"
      category_logo: "logo-php.svg"
      category_og_image: "logo-php.png"
      category_desc: "天才星人まくのPHPノート"
      category_long_desc: "サーバサイド言語の世界で一世を風靡した PHP。CodeIgnitor は RoR よりも手軽でオススメ。"
  -
    scope:
      path: "python"
      type: "pages"
    values:
      category_title: "Python"
      category_id: "python"
      category_logo: "logo-python.png"
      category_og_image: "logo-python.png"
      category_desc: "天才星人まくのPythonノート"
      category_long_desc: "機械学習の世界で最も人気なプログラミング言語 Python の使い方。"
  -
    scope:
      path: "r"
      type: "pages"
    values:
      category_title: "R"
      category_id: "r"
      category_logo: "logo-r.svg"
      category_og_image: "logo-r.png"
      category_desc: "天才星人まくのRノート"
      category_long_desc: "統計解析やグラフプロットに便利な R の入門。"
  -
    scope:
      path: "ruby"
      type: "pages"
    values:
      category_title: "Ruby"
      category_id: "ruby"
      category_logo: "logo-ruby.jpg"
      category_og_image: "logo-ruby.jpg"
      category_desc: "天才星人まくのRubyノート"
      category_long_desc: "日本で生まれたオブジェクト指向言語 Ruby の使い方。"
  -
    scope:
      path: "rust"
      type: "pages"
    values:
      category_title: "Rust"
      category_id: "rust"
      category_logo: "logo-rust.svg"
      category_og_image: "logo-rust.png"
      category_desc: "天才星人まくのRustノート"
      category_long_desc: "C/C++ からの乗り換えが進行中。"
  -
    scope:
      path: "sass"
      type: "pages"
    values:
      category_title: "Sass"
      category_id: "sass"
      category_logo: "logo-sass.svg"
      category_og_image: "logo-sass.png"
      category_desc: "天才星人まくのSassノート"
      category_long_desc: "CSSはSassを使って効率的に作りましょう。"
  -
    scope:
      path: "sed"
      type: "pages"
    values:
      category_title: "sed/awk"
      category_id: "sed"
      category_logo: "logo-text.png"
      category_og_image: "logo-text.png"
      category_desc: "天才星人まくのSed/Awkノート"
      category_long_desc: "Linux 系のコマンドを用いたテキスト処理いろいろ。"
  -
    scope:
      path: "sql"
      type: "pages"
    values:
      category_title: "SQL"
      category_id: "sql"
      category_logo: "logo-sql.svg"
      category_og_image: "logo-sql.png"
      category_desc: "天才星人まくのSQLノート"
      category_long_desc: "SQL 全般や SQLite、MySQL に関するメモ。"
  -
    scope:
      path: "tradestation"
      type: "pages"
    values:
      category_title: "トレードステーション"
      category_id: "tradestation"
      category_logo: "logo-tradestation.png"
      category_og_image: "logo-tradestation.png"
      category_desc: "天才星人まくのトレステノート"
      category_long_desc: "最強のトレードソフト TradeStation。EasyLanguage によるシストレ用プログラムなど。"
  -
    scope:
      path: "vagrant"
      type: "pages"
    values:
      category_title: "Vagrant"
      category_id: "vagrant"
      category_logo: "logo-vagrant.svg"
      category_og_image: "logo-vagrant.png"
      category_desc: "天才星人まくのVagrantノート"
      category_long_desc: "仮想環境の立ち上げ＆設定の自動化に関するメモ。"
  -
    scope:
      path: "vba"
      type: "pages"
    values:
      category_title: "VBA"
      category_id: "vba"
      category_logo: "logo-vba.svg"
      category_og_image: "logo-vba.png"
      category_desc: "天才星人まくのVBAノート"
      category_long_desc: "Excel や PowerPoint まだまだ現役な VBA マクロのメモ。"
  -
    scope:
      path: "vim"
      type: "pages"
    values:
      category_title: "Vim"
      category_id: "vim"
      category_logo: "logo-vim.svg"
      category_og_image: "logo-vim.png"
      category_desc: "天才星人まくのVimノート"
      category_long_desc: "素敵なテキストエディタ Vim のメモ。"
  -
    scope:
      path: "windows"
      type: "pages"
    values:
      category_title: "Windows"
      category_id: "windows"
      category_logo: "logo-windows.jpg"
      category_og_image: "logo-windows.jpg"
      category_desc: "天才星人まくのWindowsノート"
      category_long_desc: "Windows の便利な使い方や、バッチファイルによるプログラミング方法。"

