/*
 * Generated by gdbus-codegen 2.32.1. DO NOT EDIT.
 *
 * The license of this code is the same as for the source it was derived from.
 */

#ifndef __CALC_H__
#define __CALC_H__

#include <gio/gio.h>

G_BEGIN_DECLS


/* ------------------------------------------------------------------------ */
/* Declarations for com.example.MyApp.Calc */

#define TYPE_COM_EXAMPLE_MY_APP_CALC (com_example_my_app_calc_get_type ())
#define COM_EXAMPLE_MY_APP_CALC(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_COM_EXAMPLE_MY_APP_CALC, ComExampleMyAppCalc))
#define IS_COM_EXAMPLE_MY_APP_CALC(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_COM_EXAMPLE_MY_APP_CALC))
#define COM_EXAMPLE_MY_APP_CALC_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), TYPE_COM_EXAMPLE_MY_APP_CALC, ComExampleMyAppCalcIface))

struct _ComExampleMyAppCalc;
typedef struct _ComExampleMyAppCalc ComExampleMyAppCalc;
typedef struct _ComExampleMyAppCalcIface ComExampleMyAppCalcIface;

struct _ComExampleMyAppCalcIface
{
  GTypeInterface parent_iface;

  gboolean (*handle_add) (
    ComExampleMyAppCalc *object,
    GDBusMethodInvocation *invocation,
    gint arg_val1,
    gint arg_val2);

  gboolean (*handle_subtract) (
    ComExampleMyAppCalc *object,
    GDBusMethodInvocation *invocation,
    gint arg_val1,
    gint arg_val2);

};

GType com_example_my_app_calc_get_type (void) G_GNUC_CONST;

GDBusInterfaceInfo *com_example_my_app_calc_interface_info (void);
guint com_example_my_app_calc_override_properties (GObjectClass *klass, guint property_id_begin);


/* D-Bus method call completion functions: */
void com_example_my_app_calc_complete_add (
    ComExampleMyAppCalc *object,
    GDBusMethodInvocation *invocation,
    gint ret_val);

void com_example_my_app_calc_complete_subtract (
    ComExampleMyAppCalc *object,
    GDBusMethodInvocation *invocation,
    gint ret_val);



/* D-Bus method calls: */
void com_example_my_app_calc_call_add (
    ComExampleMyAppCalc *proxy,
    gint arg_val1,
    gint arg_val2,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean com_example_my_app_calc_call_add_finish (
    ComExampleMyAppCalc *proxy,
    gint *out_ret_val,
    GAsyncResult *res,
    GError **error);

gboolean com_example_my_app_calc_call_add_sync (
    ComExampleMyAppCalc *proxy,
    gint arg_val1,
    gint arg_val2,
    gint *out_ret_val,
    GCancellable *cancellable,
    GError **error);

void com_example_my_app_calc_call_subtract (
    ComExampleMyAppCalc *proxy,
    gint arg_val1,
    gint arg_val2,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean com_example_my_app_calc_call_subtract_finish (
    ComExampleMyAppCalc *proxy,
    gint *out_ret_val,
    GAsyncResult *res,
    GError **error);

gboolean com_example_my_app_calc_call_subtract_sync (
    ComExampleMyAppCalc *proxy,
    gint arg_val1,
    gint arg_val2,
    gint *out_ret_val,
    GCancellable *cancellable,
    GError **error);



/* ---- */

#define TYPE_COM_EXAMPLE_MY_APP_CALC_PROXY (com_example_my_app_calc_proxy_get_type ())
#define COM_EXAMPLE_MY_APP_CALC_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_COM_EXAMPLE_MY_APP_CALC_PROXY, ComExampleMyAppCalcProxy))
#define COM_EXAMPLE_MY_APP_CALC_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), TYPE_COM_EXAMPLE_MY_APP_CALC_PROXY, ComExampleMyAppCalcProxyClass))
#define COM_EXAMPLE_MY_APP_CALC_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), TYPE_COM_EXAMPLE_MY_APP_CALC_PROXY, ComExampleMyAppCalcProxyClass))
#define IS_COM_EXAMPLE_MY_APP_CALC_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_COM_EXAMPLE_MY_APP_CALC_PROXY))
#define IS_COM_EXAMPLE_MY_APP_CALC_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), TYPE_COM_EXAMPLE_MY_APP_CALC_PROXY))

typedef struct _ComExampleMyAppCalcProxy ComExampleMyAppCalcProxy;
typedef struct _ComExampleMyAppCalcProxyClass ComExampleMyAppCalcProxyClass;
typedef struct _ComExampleMyAppCalcProxyPrivate ComExampleMyAppCalcProxyPrivate;

struct _ComExampleMyAppCalcProxy
{
  /*< private >*/
  GDBusProxy parent_instance;
  ComExampleMyAppCalcProxyPrivate *priv;
};

struct _ComExampleMyAppCalcProxyClass
{
  GDBusProxyClass parent_class;
};

GType com_example_my_app_calc_proxy_get_type (void) G_GNUC_CONST;

void com_example_my_app_calc_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
ComExampleMyAppCalc *com_example_my_app_calc_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error);
ComExampleMyAppCalc *com_example_my_app_calc_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);

void com_example_my_app_calc_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
ComExampleMyAppCalc *com_example_my_app_calc_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
ComExampleMyAppCalc *com_example_my_app_calc_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);


/* ---- */

#define TYPE_COM_EXAMPLE_MY_APP_CALC_SKELETON (com_example_my_app_calc_skeleton_get_type ())
#define COM_EXAMPLE_MY_APP_CALC_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_COM_EXAMPLE_MY_APP_CALC_SKELETON, ComExampleMyAppCalcSkeleton))
#define COM_EXAMPLE_MY_APP_CALC_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), TYPE_COM_EXAMPLE_MY_APP_CALC_SKELETON, ComExampleMyAppCalcSkeletonClass))
#define COM_EXAMPLE_MY_APP_CALC_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), TYPE_COM_EXAMPLE_MY_APP_CALC_SKELETON, ComExampleMyAppCalcSkeletonClass))
#define IS_COM_EXAMPLE_MY_APP_CALC_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_COM_EXAMPLE_MY_APP_CALC_SKELETON))
#define IS_COM_EXAMPLE_MY_APP_CALC_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), TYPE_COM_EXAMPLE_MY_APP_CALC_SKELETON))

typedef struct _ComExampleMyAppCalcSkeleton ComExampleMyAppCalcSkeleton;
typedef struct _ComExampleMyAppCalcSkeletonClass ComExampleMyAppCalcSkeletonClass;
typedef struct _ComExampleMyAppCalcSkeletonPrivate ComExampleMyAppCalcSkeletonPrivate;

struct _ComExampleMyAppCalcSkeleton
{
  /*< private >*/
  GDBusInterfaceSkeleton parent_instance;
  ComExampleMyAppCalcSkeletonPrivate *priv;
};

struct _ComExampleMyAppCalcSkeletonClass
{
  GDBusInterfaceSkeletonClass parent_class;
};

GType com_example_my_app_calc_skeleton_get_type (void) G_GNUC_CONST;

ComExampleMyAppCalc *com_example_my_app_calc_skeleton_new (void);


G_END_DECLS

#endif /* __CALC_H__ */
