name: Build and deploy Hugo site to GitHub Pages

on:
  push:
    branches: [main, master]

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0  # Fetch all history for .GitInfo and .Lastmod

      - name: Install Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.136.5'
          extended: true  # Enable scss

      - name: Build with Hugo
        run: hugo --minify --disableKinds taxonomy,term
        working-directory: hugo-files

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: hugo-files/public
